### PR TITLE
(#26) Fix tracking of unexecuted searchkick queries and tracking of queries across multiple indices

### LINKED ISSUE #26: Errors when using Searchkick with option execute => false
When creating queries with searchkick using the option "execute: false" in combination with searchjoy, the Track module tries to append the Search object to the Searchkick::Query, which doesn´t have the respective attribute, thus leading to errors. 

Relevant references: 
- searchjoy/lib/searchjoy/track.rb:8
- searchjoy/lib/searchjoy.rb:41

Additionally, when creating queries with searchkick using the option "index_name", Search objects without search_type are created. This leads to errors in SearchesController#set_searches_types

Relevant references:
- searchjoy/app/controllers/searchjoy/searches_controller.rb:41

Tested with:
- searchkick 1.2.1
- searchjoy 0.0.10

### PR DESCRIPTION
**Pull request by patrick-nits**
This pull request fixes #26

### CODE REVIEW

**Comment by ankane** [comment]
Hey @patrick-nits, thanks for the PR! I'll leave a few comments inline.

File: app/controllers/searchjoy/searches_controller.rb [hunk 1]
```diff
@@ -39,7 +39,8 @@ def recent
     protected
 
     def set_search_types
-      @search_types = Searchjoy::Search.uniq.pluck(:search_type).sort
+      @search_types = Searchjoy::Search.uniq.pluck(:search_type)
+      @search_types = @search_types.reject(&:blank?).sort + @search_types.select(&:blank?)
```
Comment (ankane) [inline app/controllers/searchjoy/searches_controller.rb]: Is there any reason to include `blank?` search types?

File: lib/searchjoy/track.rb [hunk 2]
```diff
@@ -5,11 +5,23 @@ def search_with_track(term, options = {}, &block)
         block.call(body) if block
       end
 
-      if options[:track]
+      if options[:track] && options[:execute]
```
Comment (ankane) [inline lib/searchjoy/track.rb]: Is this needed if we hook into the `execute` method instead? Passing `execute: true` will cause searches to be inserted twice.

File: lib/searchjoy/track.rb [hunk 3]
```diff
@@ -5,11 +5,23 @@ def search_with_track(term, options = {}, &block)
...
       end
       results
     end
+
+    def execute_with_track
+      results = execute_without_track
+
+      if options[:track]
+        attributes = options[:track] == true ? {} : options[:track]
+        search_type = klass.try(:name) || options[:index_name].join(' ')
```
Comment (ankane) [inline lib/searchjoy/track.rb]: This throws an error if index_name is `nil` or not an array.

File: app/controllers/searchjoy/searches_controller.rb (hunk 1 above)
Comment (patrick-nits) [inline app/controllers/searchjoy/searches_controller.rb]: When using searches across **multiple indices** (with searchkick) there is no `name` nor `klass` available, thus the `search_type` will be blank. This results in displaying in an error when trying to access the searchjoy statistics panel. (Can´t do `[nil, 'String'].sort`)

File: lib/searchjoy/track.rb (hunk 2 above)
Comment (patrick-nits) [inline lib/searchjoy/track.rb]: Mh, good point. I guess hooking into `execute`will be sufficient. I´ll update the PR as soon as I can.

File: lib/searchjoy/track.rb (hunk 3 above)
Comment (patrick-nits) [inline lib/searchjoy/track.rb]: D´oh, you are right. I´ll fix this.

File: app/controllers/searchjoy/searches_controller.rb (hunk 1 above)
Comment (ankane) [inline app/controllers/searchjoy/searches_controller.rb]: Is there a reason to do the above approach rather than

```ruby
Searchjoy::Search.uniq.pluck(:search_type).reject(&:blank?).sort
```

Comment (patrick-nits) [inline app/controllers/searchjoy/searches_controller.rb]: Well, that would exclude Searches with `search_type==nil`.

**Comment by patrick-nits** [comment]
Hey @ankane, I updated the PR and removed the `search_with_track`method entirely. 
**Note**: The legacy reference in searchkick (searchkick-1.2.1/lib/searchkick/model.rb:2) for the module `Reindex` can be removed if this PR is merged.

File: app/controllers/searchjoy/searches_controller.rb (hunk 1 above)
Comment (patrick-nits) [inline app/controllers/searchjoy/searches_controller.rb]: I dont know If it is _that_ important to include/ display Searches where the search_type is blank. Maybe I have mixed some requirements of my own project into this fix.

File: lib/searchjoy/track.rb [hunk 4]
```diff
@@ -1,15 +1,22 @@
...
+    def execute_with_track
+      results = execute_without_track
 
       if options[:track]
         attributes = options[:track] == true ? {} : options[:track]
-        results.search = Searchjoy::Search.create({search_type: name, query: term, results_count: results.total_count}.merge(attributes))
+        search_type = if klass.respond_to?(:name) && klass.name.present?
+                        klass.name
+                      elsif options[:index_name].is_a? Array
+                        options[:index_name].join(' ')
```
Comment (ankane) [inline lib/searchjoy/track.rb]: Would probably be good to use `index_name` if it's a string as well.

```ruby
Array(options[:index_name]).join(", ")
```

File: lib/searchjoy/track.rb [hunk 5]
```diff
@@ -1,15 +1,22 @@
...
+                      else
+                        nil
```
Comment (ankane) [inline lib/searchjoy/track.rb]: What if we had a default like `All Indices`?

File: lib/searchjoy.rb [hunk 6]
```diff
@@ -9,6 +9,7 @@
 module Searchjoy
   # time zone
   mattr_reader :time_zone
+
```
Comment (ankane) [inline lib/searchjoy.rb]: Can you remove the added whitespace lines to keep the diff minimal?

**Comment by patrick-nits** [comment]
Updated to fix your comments.

**Comment by ankane** [comment]
Great, thanks @patrick-nits 👍
